info_dict = {
    0: "Entrance 1",
    1: "Entrance 2",
    2: "Entrance 3",
    3: "Entrance 4",
    4: "Escalator going down",
    5: "Escalator going up",
    6: "Station office",
    7: "Men toilet",
    8: "Women toilet",
    9: "Elevator",
    10: "Ticket Gate",
    11: "Stairs going down",
    12: "Stairs going up",
}
